# Generated by Django 5.2.2 on 2025-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=10)),
                ('admin_email', models.CharField(max_length=10)),
                ('admin_password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_admin',
            },
        ),
    ]
