# Generated by Django 5.2.3 on 2025-06-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0002_tbl_newuser_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'tbl_pincode',
            },
        ),
        migrations.CreateModel(
            name='tbl_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rent_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('bills_included', models.BooleanField(default=False)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('min_stay', models.CharField(max_length=50)),
                ('max_stay', models.CharField(max_length=50)),
                ('days_available', models.CharField(max_length=100)),
                ('short_term', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('room_in_existing', 'Room in existing share'), ('studio', 'Studio/2 bed flats'), ('whole_property', 'Whole property')], max_length=50)),
                ('room_size', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room')], max_length=10)),
                ('room_furnishing', models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished')], max_length=15)),
                ('is_en_suite', models.BooleanField(default=False)),
                ('no_of_rooms', models.PositiveIntegerField()),
                ('share_occupation', models.CharField(choices=[('professional', 'Professional'), ('student', 'Student')], max_length=20)),
                ('room_for', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('couple', 'Couple')], max_length=10)),
                ('share_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], max_length=10)),
                ('occupant_age', models.CharField(max_length=50)),
                ('household_option', models.CharField(choices=[('lgbt', 'LGBT'), ('veg', 'Vegetarian/Vegan preferred')], max_length=30)),
                ('no_of_bedrooms', models.PositiveIntegerField()),
                ('property_preference', models.CharField(max_length=100)),
                ('property_habit', models.CharField(choices=[('smoking', 'Smoking'), ('non_smoking', 'Non-smoking')], max_length=20)),
                ('room_suitable_for', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], max_length=10)),
            ],
            options={
                'db_table': 'tbl_property',
            },
        ),
        migrations.CreateModel(
            name='tbl_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_title', models.CharField(max_length=80)),
                ('house_description', models.CharField(max_length=300)),
                ('house_category', models.CharField(max_length=80)),
                ('house_price', models.IntegerField()),
                ('house_location', models.CharField(max_length=50)),
                ('house_status', models.CharField(choices=[('1', 'Available'), ('0', 'Not Available')], default='1', max_length=20)),
                ('house_address', models.TextField()),
                ('house_pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_pincode')),
            ],
            options={
                'db_table': 'tbl_house',
            },
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_pincode')),
            ],
            options={
                'db_table': 'tbl_place',
            },
        ),
        migrations.CreateModel(
            name='tbl_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_admin', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending (Admin has NOT replied)'), ('replied', 'Replied (Admin has answered)')], default='pending', max_length=10)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='Guest.tbl_newuser')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.tbl_property')),
            ],
            options={
                'db_table': 'tbl_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='room_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Admin.tbl_property')),
            ],
            options={
                'db_table': 'tbl_gallery',
            },
        ),
        migrations.CreateModel(
            name='tbl_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=80)),
                ('room_description', models.CharField(max_length=300)),
                ('room_category', models.CharField(max_length=80)),
                ('room_rate', models.IntegerField()),
                ('room_location', models.CharField(max_length=80)),
                ('room_status', models.CharField(choices=[('1', 'Available'), ('0', 'Not Available')], default='1', max_length=20)),
                ('room_address', models.TextField()),
                ('room_pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_pincode')),
            ],
            options={
                'db_table': 'tbl_room',
            },
        ),
    ]
