# Generated by Django 5.2.3 on 2025-06-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_pincode_tbl_property_tbl_house_tbl_place_and_more'),
    ]

    operations = [
    ]
