# Generated by Django 5.2.3 on 2025-06-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_favourite'),
        ('Guest', '0002_tbl_newuser_user_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='tbl_favourite',
        ),
    ]
