# Generated by Django 5.2.3 on 2025-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_rename_favourite_tbl_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_password',
            field=models.CharField(max_length=30),
        ),
    ]
