# Generated by Django 5.2.3 on 2025-07-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_tbl_admin_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_place',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='tbl_room',
            name='room_pincode',
        ),
        migrations.DeleteModel(
            name='tbl_house',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.DeleteModel(
            name='tbl_pincode',
        ),
        migrations.DeleteModel(
            name='tbl_room',
        ),
    ]
