# Generated by Django 5.2.3 on 2025-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_newuser',
            name='user_phone',
            field=models.CharField(default='+0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='tbl_newuser',
            name='user_firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_newuser',
            name='user_lastname',
            field=models.CharField(max_length=20),
        ),
    ]
