# Generated by Django 5.0 on 2025-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_newuser_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_newuser',
            name='verify_status',
            field=models.IntegerField(default=0),
        ),
    ]
