# Generated by Django 5.2.3 on 2025-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_newuser_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_newuser',
            name='verification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
