# Generated by Django 5.2.3 on 2025-07-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_newuser_verification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_newuser',
            name='user_password',
            field=models.CharField(max_length=150),
        ),
    ]
