# Generated by Django 5.2.3 on 2025-07-16 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_remove_tbl_place_pincode_and_more'),
        ('Guest', '0005_alter_tbl_newuser_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=400)),
                ('propert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
    ]
