# Generated by Django 5.2.3 on 2025-07-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_review',
            old_name='propert',
            new_name='property',
        ),
    ]
