# Generated by Django 5.2.3 on 2025-08-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_delete_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_review',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tbl_review',
            name='user',
        ),
        migrations.AlterField(
            model_name='tbl_review',
            name='review',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='tbl_review',
            table='tbl_feedback',
        ),
    ]
