# Generated by Django 5.2.3 on 2025-08-04 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_newuser_user_password'),
        ('User', '0007_remove_tbl_review_property_remove_tbl_review_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
